name: Docker build
on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  schedule:
    - cron: '0 2 * * *'
jobs:
  space_robots:
    runs-on: ubuntu-20.04
    steps:
      - name: "Free up disk space"
        run: |
          sudo apt-get -qq purge "ghc*"
          sudo apt-get clean
          # cleanup docker images not used by us
          docker system prune -af
          # free up a lot of stuff from /usr/local
          sudo rm -rf /usr/local
          df -h
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up buildx
        uses: docker/setup-buildx-action@v1
      - name: Build moveit2 image
        uses: docker/build-push-action@v2
        with:
          context: moveit2
          push: false
          tags: openrobotics/moveit2
          cache-from: type=gha
          cache-to: type=gha,mode=max
          no-cache: true
      - name: Build space robots demo image
        uses: docker/build-push-action@v2
        with:
          context: space_robots
          push: false
          tags: space_robots
          cache-from: type=gha
          cache-to: type=gha,mode=max
          no-cache: true
